### ISSUE TITLE
Comments do not appear due to a 500 error

### ISSUE THREAD

**Issue by Avenred** [geauser/internetcheckpoint#18]
New comments do not appear when viewing a video as the server returns a 500 error code:
![firefox_1718302829_4296](https://github.com/geauser/internetcheckpoint/assets/13921970/0da49143-26f2-4b69-9fa4-334355c70aa4)

**Comment by geauser** [comment]
Hi @Avenred Im aware of the issue.

Its because the db provider I used canceled their free offer and now it costs $39/month. I just need the time to migrate to another db provider. Once this is done comments will appear back on the website.

**Comment by geauser** [comment]
It's fixed! @Avenred
